#!/bin/sh
flatpak list --app --columns=name,application,version,branch,origin \
	| jq -rRs 'split("\n")[1:-1] | map([split("\t")][] | {
		"Name": .[0],
		"ID": .[1],
		"version": .[2],
		"branch": .[3],
		"origin": .[4]
	})' | yq read - -P
