#!/bin/sh
#
# this gets run when git commit is called and if it returns anything
# other than 0 it will prevent the commit from being made.
# Send output to stderr
exec 1>&2

git diff --cached --exit-code --quiet && exit 0

porcelain="$(git status --porcelain)"

get() {
	path="$(git diff --staged --name-only | grep 'template$')"
	sed -n "s/^$1=//p" "$path" 2>/dev/null ||
	# if the sed fails then we get the basename of the dirname
	# we give priority to the upmost result.
	if [ "$1" = "pkgname" ]; then
		basename "$(dirname "$(git diff --staged --name-only | grep srcpkgs/ | head -n 1)")"
	fi
}

has() {
	path="$(git diff --staged --name-only | grep 'template$' | head -n1)"
	grep -q "^$1" "$path" 
}

out() {
	printf "%s\\n" "$1"
}

formalize_template() {
	templates="$(git diff --staged --name-only | grep 'template$')"
	[ -z "$templates" ] && return
	for template in $templates; do
		template-formalize "$template"
		[ -z "$(git diff --name-only)" ] && continue
		printf "%s" "$templates" > .commit.o
	done
}

if out "$porcelain" | grep -q 'template$'; then
	[ "$IGNORE_XLINT" ] || if ! xlint "$(git diff --staged --name-only | grep 'template$')"; then
		exit 1
	fi
fi

formalize_template

exit 0
