#!/bin/sh
#
# This hook adds prefix "<repo>/<pkgname>: " to the commit message when
# committing changes of a single package.
#
MSG_FILE="$1"
SOURCE="$2"

longest_common_prefix() {
	awk -F/ '
		(NR == 1) { split($0, prefix); prefix_len = NF }
		(NR > 1) {
			for (i = 1; i <= prefix_len; i++) {
				if (prefix[i] != $i) {
					prefix_len = i - 1; break
				}
			}
		}
		(prefix_len == 0) { exit }
		END {
			res = prefix[1]
			for (i = 2; i <= prefix_len; i++) {
				res = res FS prefix[i]
			}
			print(res)
		}'
}

prepend_msg() {
	local prefix="$1"

	printf '%s\n%s\n' "$prefix" "$(cat "$MSG_FILE")" > "$MSG_FILE"
}

newpkgver() {
	printf 'update to %s' "$(git diff --cached HEAD -- '**/APKBUILD' | grep -m1 '^+pkgver=.*' | cut -d= -f2)"
}

isupdate() {
	git diff --cached HEAD -- '**/APKBUILD' | grep -E -q '^(\+|-)pkgver='
}

repomv() {
	git diff --name-status --cached --diff-filter=ACMR HEAD -- '**/APKBUILD' | while read -r _ from to; do
		printf 'move from %s to %s\n' "$(echo "$from" | cut -d / -f1)" "$(echo "$to" | cut -d / -f1)"
	done
}

context() {
	case "$(git diff-index --name-status --cached --diff-filter=ACMR HEAD -- '**/APKBUILD' | head -1)" in
		A*) echo "new aport" ;;
		M*) isupdate && newpkgver ;;
	esac
}

# Do nothing if message has been given using -m, template, merge etc.
[ -z "$SOURCE" ] || exit 0

lcp=$(git diff-index --name-only --cached HEAD | longest_common_prefix)

case "$lcp" in
	[^.]*/*) prepend_msg "$(echo "$lcp" | cut -d/ -f1-2): $(context)";;
	*)
		pkgname="$(git diff-index --name-only --cached HEAD --diff-filter=ACMR -- '**/APKBUILD')"
		pkgname="${pkgname%/*}"
		pkgname="${pkgname#*/}"
		prepend_msg "$pkgname: $(repomv)";;
esac

exit 0
