# Delete the whole word, or from the part of the word we are in, until the end
map global normal '<c-w>' 'bd' -docstring 'Vim-style delete whole word'
# Insert variant
map global insert '<c-w>' '<esc>bdi' -docstring 'Vim-style delete whole word'

# Select the whole line
map global normal '<s-v>' 'x' -docstring 'Shift + v to select whole line'

# This is currently broken
map global normal '<c-left>' '<b>' -docstring 'Go back to previous word'
map global normal '<c-right>' '<e>' -docstring 'Go to the next word to next word'

# Keybind to go to start and and end of the line
map global normal '<c-up>' 'gh' -docstring 'Go to the beginning of the line'
map global normal '<c-down>' 'gl' -docstring 'Go to the end of the line'

map global insert '<c-up>' '<esc>ghi' -docstring 'Go to the beginning of the line'
map global insert '<c-down>' '<esc>gli' -docstring 'Go to the end of the line'

# If we press enter in normal mode then we save and quit, this is even faster
# than our :x which is faster than neovim
hook global NormalKey <ret> write-quit

# If we do ':' then press x then we save-quit, even faster than our previous
# neovim configuration
map global prompt x write-quit<ret>

# Departure from my previous 4
set-option global tabstop 2
set-option global indentwidth 2

# Yank and Paste from world clipboard
map global normal p -docstring 'paste from clipboard' '!paste<ret>'
map global normal y -docstring 'copy to clipboard' '<a-|>copy<ret>'
map global normal d -docstring 'cut to clipboard' '|xsel -bi<ret>'

# Use super quicky-fast ripgrep
set-option global grepcmd 'rg -Hn --no-heading'

# Make search case insensitive
map global normal / /(?i) -docstring 'case insensitive search'

# Custom colorscheme
colorscheme gruvbox

# Define function on APKBUILDs to upgrade the pkgver
hook global BufCreate (.*/)?APKBUILD %{
	define-command -docstring 'Upgrade pkgver to another version' \
	up -params 1 %{
  	execute-keys '%s(?S)^pkgver=.*<ret>cpkgver=' %arg{1}<esc>
  	execute-keys -draft '%s(?S)^pkgrel=.*<ret>cpkgrel=0<esc>'
	}
}

