#!/bin/sh

if [ -e "$BSPWM_STATE" ]; then
	bspc wm -l "$BSPWM_STATE"
	rm -f -- "$BSPWM_STATE"
fi

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config active_border_color '#FFFFFF'
bspc config normal_border_color '#FFFFFF'
bspc config focused_border_color '#FFFFFF'

bspc config pointer_follows_focus true

# Make all windows floating
bspc rule -a "*" state=floating

bspc rule -a Firefox:Navigator desktop=^1 rectangle=1376x733+-1+-1 follow=on
bspc rule -a TelegramDesktop:Telegram desktop=^2 rectangle=1376x733+-1+-1 follow=on

bspc rule -a Firefox:SessionManager desktop=^1 layer=above

# Adopt orphans
bspc wm -o

for area in focus desktop date clock spacing mail memory battery volume music; do
	pgrep "$area"-bar >/dev/null && pkill "$area"-bar
	run-bar "$area" &
done
	
for area in focus desktop date clock spacing mail memory battery volume music; do
	# This needs to be in another loop because there is a race condition between
	# the bar forking and this being able to find it
	xdo above -t "$(xdo id -n root)" "$(xdo id -a "$area"-bar)"
done
