#!/bin/sh

if [ -e "$BSPWM_STATE" ]; then
	bspc wm -l "$BSPWM_STATE"
	rm -f -- "$BSPWM_STATE"
fi

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config active_border_color '#FFFFFF'
bspc config normal_border_color '#FFFFFF'
bspc config focused_border_color '#FFFFFF'

bspc config pointer_follows_focus true

# Make all windows floating
bspc rule -a "*" state=floating

bspc rule -a '*:quaternion' desktop=^4 rectangle=1376x733+-1+-1 follow=on
bspc rule -a '*:luakit' desktop=^1 rectangle=1376x733+-1+-1 follow=on
bspc rule -a Firefox:Navigator desktop=^1 rectangle=1376x733+-1+-1 follow=on
bspc rule -a TelegramDesktop:telegram-desktop desktop=^2 rectangle=1376x733+-1+-1 follow=on
bspc rule -a '*:mpv' desktop=^4 rectangle=1376x733+-1+-1 follow=on

bspc rule -a Firefox:SessionManager desktop=^1 layer=above

# Adopt orphans
bspc wm -o

pgrep -u "$(id -u)" -x polybar && pkill -u "$(id -u)" -x polybar

polybar main --reload
